github: vantisCorp
patreon: vantisplayer
open_collective: vantis
ko_fi: vantis
tidelift: npm/vantis-player
community_bridge: vantis-media-player
liberapay: vantis
issuehunt: vantisCorp/Vantis-Media-Player
otechie: vantis
custom: ['https://paypal.me/vantisplayer', 'https://buymeacoffee.com/vantis']