# These are supported funding model platforms

github: [vantisCorp]
patreon: vantis
open_collective: vantis
ko_fi: vantis
tidelift: # Replace with your Tidelift package name
community_bridge: # Replace with your Community Bridge project name
liberapay: vantis
issuehunt: vantis
otechie: vantis
custom: ['https://paypal.me/vantis', 'https://vantis.ai/donate']