//! Automated Video Tagging
//! 
//! AI-powered automatic tagging for video content:
//! - Scene detection and classification
//! - Object and face detection
//! - Activity recognition
//! - Content-based tag generation
//! - Confidence-based tag ranking

use anyhow::{Result, bail};
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::sync::Arc;
use parking_lot::RwLock;
use tracing::{info, debug};

// ============================================================================
// Tag Types
// ============================================================================

/// Video tag category
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TagCategory {
    /// Content type (movie, series, documentary, etc.)
    ContentType,
    /// Genre tags
    Genre,
    /// Visual elements
    Visual,
    /// Audio elements
    Audio,
    /// People/actors
    People,
    /// Locations
    Location,
    /// Activities
    Activity,
    /// Objects
    Object,
    /// Mood/atmosphere
    Mood,
    /// Technical quality
    Technical,
    /// Custom user tag
    Custom,
}

impl TagCategory {
    /// Get display name
    pub fn display_name(&self) -> &'static str {
        match self {
            Self::ContentType => "Content Type",
            Self::Genre => "Genre",
            Self::Visual => "Visual",
            Self::Audio => "Audio",
            Self::People => "People",
            Self::Location => "Location",
            Self::Activity => "Activity",
            Self::Object => "Objects",
            Self::Mood => "Mood",
            Self::Technical => "Technical",
            Self::Custom => "Custom",
        }
    }
}

/// Video tag with confidence score
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VideoTag {
    /// Tag text
    pub tag: String,
    
    /// Category
    pub category: TagCategory,
    
    /// Confidence score (0.0 - 1.0)
    pub confidence: f32,
    
    /// Source of the tag
    pub source: TagSource,
    
    /// Timestamps where this tag appears (in seconds)
    pub timestamps: Vec<f64>,
    
    /// Is this tag verified by user
    pub verified: bool,
}

impl VideoTag {
    /// Create a new tag
    pub fn new(tag: &str, category: TagCategory, confidence: f32) -> Self {
        Self {
            tag: tag.to_string(),
            category,
            confidence,
            source: TagSource::AutoGenerated,
            timestamps: Vec::new(),
            verified: false,
        }
    }
    
    /// Add timestamp
    pub fn add_timestamp(&mut self, ts: f64) {
        if !self.timestamps.contains(&ts) {
            self.timestamps.push(ts);
        }
    }
    
    /// Merge with another tag
    pub fn merge(&mut self, other: &VideoTag) {
        // Average confidence
        self.confidence = (self.confidence + other.confidence) / 2.0;
        
        // Merge timestamps
        for ts in &other.timestamps {
            self.add_timestamp(*ts);
        }
    }
}

/// Source of a tag
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TagSource {
    /// Auto-generated by AI
    AutoGenerated,
    /// From metadata
    Metadata,
    /// From user input
    UserInput,
    /// From external API (IMDb, TMDB, etc.)
    ExternalAPI,
    /// From filename
    Filename,
}

// ============================================================================
// Tagging Result
// ============================================================================

/// Result of video tagging
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaggingResult {
    /// Video ID
    pub video_id: String,
    
    /// All tags
    pub tags: Vec<VideoTag>,
    
    /// Processing time in seconds
    pub processing_time: f32,
    
    /// Frames analyzed
    pub frames_analyzed: u32,
    
    /// Confidence threshold used
    pub confidence_threshold: f32,
    
    /// Warnings or notes
    pub notes: Vec<String>,
}

impl TaggingResult {
    /// Create a new result
    pub fn new(video_id: &str) -> Self {
        Self {
            video_id: video_id.to_string(),
            tags: Vec::new(),
            processing_time: 0.0,
            frames_analyzed: 0,
            confidence_threshold: 0.5,
            notes: Vec::new(),
        }
    }
    
    /// Add a tag
    pub fn add_tag(&mut self, tag: VideoTag) {
        self.tags.push(tag);
    }
    
    /// Get tags by category
    pub fn tags_by_category(&self, category: TagCategory) -> Vec<&VideoTag> {
        self.tags.iter().filter(|t| t.category == category).collect()
    }
    
    /// Get tags above confidence threshold
    pub fn high_confidence_tags(&self, threshold: f32) -> Vec<&VideoTag> {
        self.tags.iter().filter(|t| t.confidence >= threshold).collect()
    }
    
    /// Sort tags by confidence
    pub fn sort_by_confidence(&mut self) {
        self.tags.sort_by(|a, b| b.confidence.partial_cmp(&a.confidence).unwrap_or(std::cmp::Ordering::Equal));
    }
    
    /// Get unique tag values
    pub fn unique_tags(&self) -> HashSet<&str> {
        self.tags.iter().map(|t| t.tag.as_str()).collect()
    }
}

// ============================================================================
// Tagging Configuration
// ============================================================================

/// Configuration for video tagging
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaggingConfig {
    /// Enable scene detection
    pub enable_scene_detection: bool,
    
    /// Enable object detection
    pub enable_object_detection: bool,
    
    /// Enable face detection
    pub enable_face_detection: bool,
    
    /// Enable activity recognition
    pub enable_activity_recognition: bool,
    
    /// Enable audio analysis
    pub enable_audio_analysis: bool,
    
    /// Enable location detection
    pub enable_location_detection: bool,
    
    /// Minimum confidence threshold
    pub min_confidence: f32,
    
    /// Maximum tags to generate per category
    pub max_tags_per_category: usize,
    
    /// Frame sampling interval (analyze 1 frame every N seconds)
    pub frame_sample_interval: f32,
    
    /// Enable filename-based tagging
    pub enable_filename_tagging: bool,
    
    /// Enable metadata tagging
    pub enable_metadata_tagging: bool,
}

impl Default for TaggingConfig {
    fn default() -> Self {
        Self {
            enable_scene_detection: true,
            enable_object_detection: true,
            enable_face_detection: false, // Privacy consideration
            enable_activity_recognition: true,
            enable_audio_analysis: true,
            enable_location_detection: true,
            min_confidence: 0.5,
            max_tags_per_category: 10,
            frame_sample_interval: 5.0,
            enable_filename_tagging: true,
            enable_metadata_tagging: true,
        }
    }
}

// ============================================================================
// Automated Video Tagger
// ============================================================================

/// Automated video tagger
pub struct AutomatedVideoTagger {
    /// Configuration
    config: TaggingConfig,
    
    /// Object detection model loaded
    object_model_loaded: bool,
    
    /// Scene classification model loaded
    scene_model_loaded: bool,
    
    /// Activity model loaded
    activity_model_loaded: bool,
    
    /// Known tags database
    known_tags: HashMap<String, TagCategory>,
}

impl AutomatedVideoTagger {
    /// Create a new tagger
    pub fn new(config: Option<TaggingConfig>) -> Self {
        let config = config.unwrap_or_default();
        
        Self {
            config,
            object_model_loaded: false,
            scene_model_loaded: false,
            activity_model_loaded: false,
            known_tags: Self::build_known_tags(),
        }
    }
    
    /// Build known tags database
    fn build_known_tags() -> HashMap<String, TagCategory> {
        let mut tags = HashMap::new();
        
        // Genres
        for genre in &[
            "action", "adventure", "animation", "comedy", "crime", "documentary",
            "drama", "family", "fantasy", "horror", "musical", "mystery", "romance",
            "sci-fi", "thriller", "war", "western", "biography", "history", "sport",
        ] {
            tags.insert(genre.to_string(), TagCategory::Genre);
        }
        
        // Visual elements
        for visual in &[
            "sunset", "beach", "mountain", "forest", "city", "ocean", "desert",
            "night", "rain", "snow", "fire", "explosion", "car chase", "fight",
            "dance", "concert", "party", "wedding", "funeral", "battle",
        ] {
            tags.insert(visual.to_string(), TagCategory::Visual);
        }
        
        // Activities
        for activity in &[
            "running", "swimming", "driving", "flying", "fighting", "dancing",
            "singing", "cooking", "eating", "drinking", "talking", "kissing",
            "hugging", "crying", "laughing", "walking", "sitting", "sleeping",
        ] {
            tags.insert(activity.to_string(), TagCategory::Activity);
        }
        
        // Objects
        for object in &[
            "car", "plane", "boat", "train", "gun", "sword", "phone", "computer",
            "book", "newspaper", "money", "jewelry", "flower", "animal", "dog", "cat",
        ] {
            tags.insert(object.to_string(), TagCategory::Object);
        }
        
        // Moods
        for mood in &[
            "suspenseful", "romantic", "scary", "funny", "sad", "exciting",
            "peaceful", "intense", "dramatic", "mysterious", "uplifting",
        ] {
            tags.insert(mood.to_string(), TagCategory::Mood);
        }
        
        tags
    }
    
    /// Tag a video file
    pub async fn tag_video(&self, video_path: &str) -> Result<TaggingResult> {
        let start = std::time::Instant::now();
        let video_id = std::path::Path::new(video_path)
            .file_stem()
            .map(|s| s.to_string_lossy().to_string())
            .unwrap_or_else(|| video_path.to_string());
        
        info!("🏷️ Tagging video: {}", video_path);
        
        let mut result = TaggingResult::new(&video_id);
        
        // Filename-based tagging
        if self.config.enable_filename_tagging {
            let filename_tags = self.extract_filename_tags(&video_id);
            for tag in filename_tags {
                result.add_tag(tag);
            }
        }
        
        // Scene detection
        if self.config.enable_scene_detection {
            let scene_tags = self.detect_scenes(video_path).await?;
            for tag in scene_tags {
                result.add_tag(tag);
            }
            result.notes.push("Scene detection completed".to_string());
        }
        
        // Object detection
        if self.config.enable_object_detection {
            let object_tags = self.detect_objects(video_path).await?;
            for tag in object_tags {
                result.add_tag(tag);
            }
            result.notes.push("Object detection completed".to_string());
        }
        
        // Activity recognition
        if self.config.enable_activity_recognition {
            let activity_tags = self.recognize_activities(video_path).await?;
            for tag in activity_tags {
                result.add_tag(tag);
            }
            result.notes.push("Activity recognition completed".to_string());
        }
        
        // Audio analysis
        if self.config.enable_audio_analysis {
            let audio_tags = self.analyze_audio(video_path).await?;
            for tag in audio_tags {
                result.add_tag(tag);
            }
            result.notes.push("Audio analysis completed".to_string());
        }
        
        // Filter by confidence
        result.tags.retain(|t| t.confidence >= self.config.min_confidence);
        
        // Limit tags per category
        self.limit_tags_per_category(&mut result);
        
        // Sort by confidence
        result.sort_by_confidence();
        
        result.processing_time = start.elapsed().as_secs_f32();
        result.confidence_threshold = self.config.min_confidence;
        
        info!("✅ Tagging complete: {} tags generated", result.tags.len());
        
        Ok(result)
    }
    
    /// Extract tags from filename
    fn extract_filename_tags(&self, filename: &str) -> Vec<VideoTag> {
        let mut tags = Vec::new();
        let filename_lower = filename.to_lowercase();
        
        // Check for known tags in filename
        for (tag, category) in &self.known_tags {
            if filename_lower.contains(tag) {
                tags.push(VideoTag::new(tag, *category, 0.7));
            }
        }
        
        // Extract year
        let year_regex = regex_match_year(&filename_lower);
        if let Some(year) = year_regex {
            tags.push(VideoTag::new(&format!("year:{}", year), TagCategory::Custom, 0.9));
        }
        
        // Extract quality markers
        for quality in &["4k", "1080p", "720p", "hd", "bluray", "web-dl"] {
            if filename_lower.contains(quality) {
                tags.push(VideoTag::new(quality, TagCategory::Technical, 0.8));
            }
        }
        
        tags
    }
    
    /// Detect scenes in video
    async fn detect_scenes(&self, _video_path: &str) -> Result<Vec<VideoTag>> {
        // In a real implementation, this would:
        // 1. Extract keyframes
        // 2. Run scene classification model
        // 3. Return detected scene types
        
        let mut tags = Vec::new();
        
        // Placeholder: common scene types
        let scene_types = [
            ("outdoor", 0.6),
            ("indoor", 0.7),
            ("night", 0.5),
            ("day", 0.8),
        ];
        
        for (scene, confidence) in scene_types {
            if confidence >= self.config.min_confidence {
                tags.push(VideoTag::new(scene, TagCategory::Visual, confidence as f32));
            }
        }
        
        Ok(tags)
    }
    
    /// Detect objects in video
    async fn detect_objects(&self, _video_path: &str) -> Result<Vec<VideoTag>> {
        // In a real implementation, this would:
        // 1. Sample frames
        // 2. Run object detection model (YOLO, etc.)
        // 3. Aggregate detections across frames
        
        let mut tags = Vec::new();
        
        // Placeholder: common objects
        let objects = [
            ("person", 0.9),
            ("car", 0.6),
        ];
        
        for (obj, confidence) in objects {
            if confidence >= self.config.min_confidence {
                tags.push(VideoTag::new(obj, TagCategory::Object, confidence as f32));
            }
        }
        
        Ok(tags)
    }
    
    /// Recognize activities in video
    async fn recognize_activities(&self, _video_path: &str) -> Result<Vec<VideoTag>> {
        // In a real implementation, this would:
        // 1. Extract video segments
        // 2. Run activity recognition model
        // 3. Return detected activities with timestamps
        
        let mut tags = Vec::new();
        
        // Placeholder
        let activities = [
            ("talking", 0.8),
            ("walking", 0.5),
        ];
        
        for (activity, confidence) in activities {
            if confidence >= self.config.min_confidence {
                tags.push(VideoTag::new(activity, TagCategory::Activity, confidence as f32));
            }
        }
        
        Ok(tags)
    }
    
    /// Analyze audio content
    async fn analyze_audio(&self, _video_path: &str) -> Result<Vec<VideoTag>> {
        // In a real implementation, this would:
        // 1. Extract audio track
        // 2. Run audio classification
        // 3. Detect music, speech, sound effects
        
        let mut tags = Vec::new();
        
        // Placeholder
        let audio_elements = [
            ("dialogue", 0.9),
            ("music", 0.7),
        ];
        
        for (element, confidence) in audio_elements {
            if confidence >= self.config.min_confidence {
                tags.push(VideoTag::new(element, TagCategory::Audio, confidence as f32));
            }
        }
        
        Ok(tags)
    }
    
    /// Limit tags per category
    fn limit_tags_per_category(&self, result: &mut TaggingResult) {
        let mut category_counts: HashMap<TagCategory, usize> = HashMap::new();
        
        result.tags.retain(|tag| {
            let count = category_counts.entry(tag.category).or_insert(0);
            if *count < self.config.max_tags_per_category {
                *count += 1;
                true
            } else {
                false
            }
        });
    }
    
    /// Merge tagging results
    pub fn merge_results(&self, results: &[TaggingResult]) -> TaggingResult {
        let mut merged = TaggingResult::new("merged");
        
        for result in results {
            for tag in &result.tags {
                // Check if tag already exists
                if let Some(existing) = merged.tags.iter_mut().find(|t| t.tag == tag.tag && t.category == tag.category) {
                    existing.merge(tag);
                } else {
                    merged.add_tag(tag.clone());
                }
            }
            
            merged.frames_analyzed += result.frames_analyzed;
            merged.notes.extend(result.notes.clone());
        }
        
        merged.sort_by_confidence();
        merged
    }
    
    /// Get known tags for autocomplete
    pub fn get_known_tags(&self, prefix: &str) -> Vec<&String> {
        self.known_tags.keys()
            .filter(|t| t.starts_with(&prefix.to_lowercase()))
            .collect()
    }
    
    /// Get all tags in a category
    pub fn tags_in_category(&self, category: TagCategory) -> Vec<&String> {
        self.known_tags.iter()
            .filter(|(_, c)| **c == category)
            .map(|(t, _)| t)
            .collect()
    }
}

impl Default for AutomatedVideoTagger {
    fn default() -> Self {
        Self::new(None)
    }
}

// ============================================================================
// Helper Functions
// ============================================================================

/// Extract year from string using simple pattern matching
fn regex_match_year(s: &str) -> Option<String> {
    // Look for 4-digit year between 1900-2099
    for i in 0..s.len().saturating_sub(3) {
        let substr = &s[i..i+4];
        if let Ok(year) = substr.parse::<u32>() {
            if year >= 1900 && year <= 2099 {
                // Check it's not part of a larger number
                let prev_char = if i > 0 { s.chars().nth(i-1) } else { None };
                let next_char = s.chars().nth(i+4);
                
                if prev_char.map(|c| !c.is_ascii_digit()).unwrap_or(true) &&
                   next_char.map(|c| !c.is_ascii_digit()).unwrap_or(true) {
                    return Some(substr.to_string());
                }
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_tag_category_display() {
        assert_eq!(TagCategory::Genre.display_name(), "Genre");
        assert_eq!(TagCategory::Visual.display_name(), "Visual");
    }
    
    #[test]
    fn test_video_tag_creation() {
        let tag = VideoTag::new("action", TagCategory::Genre, 0.9);
        assert_eq!(tag.tag, "action");
        assert_eq!(tag.category, TagCategory::Genre);
        assert_eq!(tag.confidence, 0.9);
        assert!(!tag.verified);
    }
    
    #[test]
    fn test_tag_timestamp() {
        let mut tag = VideoTag::new("action", TagCategory::Genre, 0.9);
        tag.add_timestamp(10.0);
        tag.add_timestamp(20.0);
        tag.add_timestamp(10.0); // Duplicate
        
        assert_eq!(tag.timestamps.len(), 2);
    }
    
    #[test]
    fn test_tagging_result() {
        let mut result = TaggingResult::new("test-video");
        
        result.add_tag(VideoTag::new("action", TagCategory::Genre, 0.9));
        result.add_tag(VideoTag::new("car", TagCategory::Object, 0.7));
        
        assert_eq!(result.tags.len(), 2);
        assert_eq!(result.tags_by_category(TagCategory::Genre).len(), 1);
        assert_eq!(result.high_confidence_tags(0.8).len(), 1);
    }
    
    #[test]
    fn test_tagging_config_default() {
        let config = TaggingConfig::default();
        assert!(config.enable_scene_detection);
        assert!(config.enable_object_detection);
        assert_eq!(config.min_confidence, 0.5);
    }
    
    #[test]
    fn test_filename_tagging() {
        let tagger = AutomatedVideoTagger::new(None);
        let tags = tagger.extract_filename_tags("Action.Movie.2024.1080p");
        
        assert!(tags.iter().any(|t| t.tag == "action"));
        assert!(tags.iter().any(|t| t.tag == "1080p"));
        assert!(tags.iter().any(|t| t.tag == "year:2024"));
    }
    
    #[test]
    fn test_year_extraction() {
        assert_eq!(regex_match_year("Movie.2024.mkv"), Some("2024".to_string()));
        assert_eq!(regex_match_year("Test.1999.file"), Some("1999".to_string()));
        assert_eq!(regex_match_year("12345"), None); // Part of larger number
    }
    
    #[test]
    fn test_known_tags() {
        let tagger = AutomatedVideoTagger::new(None);
        
        let matching = tagger.get_known_tags("act");
        assert!(matching.iter().any(|t| *t == "action"));
        
        let genres = tagger.tags_in_category(TagCategory::Genre);
        assert!(genres.contains(&&"action".to_string()));
    }
}