[package]
name = "vantis-subtitles"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }
scraper = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
encoding_rs = "0.8"
charset = "0.1"
async-trait = { workspace = true }
md5 = "0.7"