name: Test Workflow

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"
      
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: List files
        run: ls -la
      
      - name: Check Rust
        run: rustc --version
